const testEvents = [
  {
    event_id: 1,
    event_name: 'Codesmith Graduation Party',
    date_time: 'Sat Sep 09 2023 16:00',
    industry: 'Information Technology',
    event_type: 'Alumni Gathering',
    event_location: 'NYC',
    total_attendees: 32,
  },
  {
    event_id: 2,
    event_name: 'Burger Conference',
    date_time: 'Thu Apr 20 2023 14:00',
    industry: 'Food and Beverage',
    event_type: 'Career Fair',
    event_location: 'San Fransisco',
    total_attendees: 237,
  },
  {
    event_id: 3,
    event_name: 'Healthcare Summit',
    date_time: 'Thu Jun 15 2023 12:00',
    industry: 'Healthcare',
    event_type: 'Conference',
    event_location: 'Chicago',
    total_attendees: 500,
  },
  {
    event_id: 4,
    event_name: 'Marketing Workshop',
    date_time: 'Fri Aug 04 2023 11:00',
    industry: 'Marketing',
    event_type: 'Webinar/Workshop',
    event_location: 'Los Angeles',
    total_attendees: 120,
  },
  {
    event_id: 5,
    event_name: 'AI & Machine Learning Expo',
    date_time: 'Wed Oct 25 2023 08:00',
    industry: 'Information Technology',
    event_type: 'Conference',
    event_location: 'Seattle',
    total_attendees: 350,
  },
  {
    event_id: 6,
    event_name: 'Green Energy Symposium',
    date_time: 'Wed Nov 08 2023 10:00',
    industry: 'Information Technology',
    event_type: 'Conference',
    event_location: 'Austin',
    total_attendees: 250,
  },
  {
    event_id: 7,
    event_name: 'Entertainment Industry Mixer',
    date_time: 'Fri Dec 01 2023 18:00',
    industry: 'Entertainment',
    event_type: 'Networking Meetup',
    event_location: 'Los Angeles',
    total_attendees: 200,
  },
  {
    event_id: 8,
    event_name: 'Financial Planning Workshop',
    date_time: 'Thu Apr 27 2023 11:00',
    industry: 'Finance',
    event_type: 'Webinar/Workshop',
    event_location: 'Boston',
    total_attendees: 80,
  },
  {
    event_id: 9,
    event_name: 'Fashion Forward Expo',
    date_time: 'Sun Apr 30 2023 12:00',
    industry: 'Entertainment',
    event_type: 'Conference',
    event_location: 'Paris',
    total_attendees: 300,
  },
  {
    event_id: 10,
    event_name: 'Startup Pitch Night',
    date_time: 'Tue May 30 2023 17:00',
    industry: 'Information Technology',
    event_type: 'Networking Meetup',
    event_location: 'San Francisco',
    total_attendees: 150,
  },
  {
      event_id: 11,
    event_name: 'Digital Marketing Trends Summit',
    date_time: 'Wed May 31 2023 17:00',
    industry: 'Marketing',
    event_type: 'Conference',
    event_location: 'London',
    total_attendees: 400,
  },
  {
    event_id: 12,
    event_name: 'Gaming Convention',
    date_time: 'Thu Jun 01 2023 17:00',
    industry: 'Entertainment',
    event_type: 'Exhibition',
    event_location: 'Tokyo',
    total_attendees: 1000,
  },
  {
    event_id: 13,
    event_name: 'FoodTech Conference',
    date_time: 'Fri Jun 02 2023 17:00',
    industry: 'Food and Beverage',
    event_type: 'Conference',
    event_location: 'Berlin',
    total_attendees: 200,
  },
  {
    event_id: 14,
    event_name: 'LegalTech Summit',
    date_time: 'Thu Apr 13 2023 17:00',
    industry: 'Legal',
    event_type: 'Conference',
    event_location: 'Washington DC',
    total_attendees: 250,
  },
];

export default testEvents