const testEvents = [
  {
    event_name: 'Codesmith Graduation Party',
    date_time: 'September 9, 2023',
    industry: 'Information Technology',
    event_type: 'Alumni Gathering',
    event_location: 'NYC',
    total_attendees: 32,
  },
  {
    event_name: 'Burger Conference',
    date_time: 'April 20, 2023',
    industry: 'Food and Beverage',
    event_type: 'Career Fair',
    event_location: 'San Fransisco',
    total_attendees: 237,
  },
  {
    event_name: 'Healthcare Summit',
    date_time: 'June 15, 2023',
    industry: 'Healthcare',
    event_type: 'Conference',
    event_location: 'Chicago',
    total_attendees: 500,
  },
  {
    event_name: 'Marketing Workshop',
    date_time: 'August 4, 2023',
    industry: 'Marketing',
    event_type: 'Webinar/Workshop',
    event_location: 'Los Angeles',
    total_attendees: 120,
  },
  {
    event_name: 'AI & Machine Learning Expo',
    date_time: 'October 25, 2023',
    industry: 'Information Technology',
    event_type: 'Conference',
    event_location: 'Seattle',
    total_attendees: 350,
  },
  {
    event_name: 'Green Energy Symposium',
    date_time: 'November 8, 2023',
    industry: 'Information Technology',
    event_type: 'Conference',
    event_location: 'Austin',
    total_attendees: 250,
  },
  {
    event_name: 'Entertainment Industry Mixer',
    date_time: 'December 1, 2023',
    industry: 'Entertainment',
    event_type: 'Networking Meetup',
    event_location: 'Los Angeles',
    total_attendees: 200,
  },
  {
    event_name: 'Financial Planning Workshop',
    date_time: 'January 12, 2024',
    industry: 'Finance',
    event_type: 'Webinar/Workshop',
    event_location: 'Boston',
    total_attendees: 80,
  },
  {
    event_name: 'Fashion Forward Expo',
    date_time: 'February 18, 2024',
    industry: 'Entertainment',
    event_type: 'Conference',
    event_location: 'Paris',
    total_attendees: 300,
    },
    {
    event_name: 'Startup Pitch Night',
    date_time: 'May 30, 2023',
    industry: 'Information Technology',
    event_type: 'Networking Meetup',
    event_location: 'San Francisco',
    total_attendees: 150,
    },
    {
    event_name: 'Digital Marketing Trends Summit',
    date_time: 'July 23, 2023',
    industry: 'Marketing',
    event_type: 'Conference',
    event_location: 'London',
    total_attendees: 400,
    },
    {
    event_name: 'Gaming Convention',
    date_time: 'September 15, 2023',
    industry: 'Entertainment',
    event_type: 'Exhibition',
    event_location: 'Tokyo',
    total_attendees: 1000,
    },
    {
    event_name: 'FoodTech Conference',
    date_time: 'October 12, 2023',
    industry: 'Food and Beverage',
    event_type: 'Conference',
    event_location: 'Berlin',
    total_attendees: 200,
    },
    {
    event_name: 'LegalTech Summit',
    date_time: 'November 17, 2023',
    industry: 'Legal',
    event_type: 'Conference',
    event_location: 'Washington DC',
    total_attendees: 250,
    },
];

export default testEvents